### ISSUE TITLE
Using a `~` in PhpStorm Docker Compose executable settings doesn't work

### ISSUE THREAD

**Issue by pyrello** [php-perfect/ddev-intellij-plugin#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

When following https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/, the docs indicate that you should enter `~/.ddev/bin/docker-compose` as the Docker Composer executable. Using the tilde (`~`) doesn't work. Entering the full path to the executable is necessary.

### Steps to reproduce

Follow the docs at https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/ and observe that entering a path using the `~/.ddev/bin/docker-compose` doesn't work. You'll see an error when entering it: `~/.ddev/bin/docker-compose does not exist`

Screenshot:
![Screen Shot 2022-11-04 at 3 54 11 PM](https://user-images.githubusercontent.com/709009/200073211-fb1552e5-f0c5-4f72-afa8-bb2a581fdfb1.png)

### Additional context
Entering this incorrectly will cause an error message in the CLI interpreter preferences for DDEV:
```
Error while parsing "/Users/user/Sites/project/.ddev/.ddev-docker-compose-full.yaml": Cannot run program "~/.ddev/bin/docker-compose" (in directory "/Users/user/Sites/project/.ddev"): error=2, No such file or directory.
```

Screenshot:
![Screen Shot 2022-11-04 at 2 22 58 PM](https://user-images.githubusercontent.com/709009/200074168-0ca10bdb-d2a5-40c1-ac96-25c1f0c48658.png)

I understand that this is not specifically related to a bug with this plugin. @rfay helped me troubleshoot and suggested that opening an issue here might help if other people have this problem.

**Comment by rfay** [comment]
As @pyrello points out, this really has nothing to do with the plugin (except that it's a recommended part of preparing for the plugin). However, it's something people might incorrectly blame on the plugin because of the coincidence. 

I should note also that PhpStorm *tried desperately* get get @pyrello not to make this mistake:
<img width="730" alt="Cursor_and_Preferences" src="https://user-images.githubusercontent.com/112444/200071802-e61fd539-1b7e-48c5-8000-d0c029cd1b08.png">

And also, he provided 
* https://github.com/drud/ddev/pull/4368
to improve DDEV docs.

**Comment by nico-loeber** [comment]
Closed due to inactivity and non related issue.
