### ISSUE TITLE
Plugin doesn't detect WSL-based docker-ce

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

PhpStorm 2023.1.4, DDEV v1.22.0-beta4

On DDEV WSL2, with docker-ce installed inside WSL2 (supported and discovered by PhpStorm) the plugin doesn't recognize that Docker is running:

![image](https://github.com/php-perfect/ddev-intellij-plugin/assets/112444/ffd0b6e7-7206-4dce-bb24-b79df3aa1f88)

### Steps to reproduce

Set up DDEV WSL2 with the recommended setup (docker-ce in WSL2) https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/

With PhpStorm running on the Windows side, open a project in WSL2 (like \\wsl$\Ubuntu\home\rfay\workspace\d10)

The plugin will report that docker is not running.

### Additional context

PhpStorm still remains weak on Windows/WSL2. It doesn't know how to use docker-compose inside WSL2, for example,

**Comment by nico-loeber** [comment]
Hey @rfay,
If docker-ce is installed inside the wsl partition the project is cloned to, there shouldn't be any problem.
Please note, that the Docker settings of phpstorm are ignored, as the plugin will create its own docker configuration.

To check if ddev is available and therfore docker is available, the plugin will try to execute `docker info` inside the root directory of the project. It will automatically detect whether this is a WSL file system path and will then use a WSL shell instead of a windows one.

```java
    public boolean isRunning(String workDirectory) {
        try {
            return ProcessExecutor.getInstance().executeCommandLine(
                    new GeneralCommandLine("docker", "info")
                            .withWorkDirectory(workDirectory),
                    5_000,
                    false
            ).getExitCode() == 0;
        } catch (ExecutionException e) {
            return false;
        }
    }
```

Could you please check if executing `docker info` in the project root returns a zero exit code in your setup?

**Comment by rfay** [comment]
I'm unable to recreate this today, so closing. `docker info` is quite successful, but I imagine it was before. It's possible that the docker client was in an unstable state when I filed this. Docker Desktop had inserted its version of everything...

**Comment by nico-loeber** [comment]
Okay, feel free to reopen this if there is aynthing we can add for compatibility.

**Comment by rfay** [comment]
I think I figured out what was going on, and it seems to be a Windows/WSL2 problem. Neither the file explorer nor PhpStorm was recognizing \\wsl$. I forced it in Explorer by clicking on "Linux", and it re-explored and got everything fixed. Then PhpStorm also saw it.
