### ISSUE TITLE
Add feature documentation

### ISSUE THREAD

**Issue by marcvangend** [php-perfect/ddev-intellij-plugin#22]
After installing the plugin (alpha2) it wasn't immediately clear to me where to find the advertised features. It would be helpful if the README documents how to enable and/or use everything the plugin adds.

Related issue: #5 proposes a different way of onboarding new users. I think both are worthwhile in their own right.

**Comment by nico-loeber** [comment]
Thanks for your feedback, @marcvangend!
We did focus on developing the plugin. Of course we plan to provide a user documentation as well as additional information for developers.
I would like to use Github Wiki for the user documentation.

https://github.com/php-perfect/ddev-intellij-plugin/wiki
Contributions are welcome!

Could you please describe what the actual problem was that you had?
Most things should work out of the box if  ddev is installed and if not you should see a message.
In case the features were available and you just didn't know where to find them #5 should fix this issue.
I would like to make everything as self explaining as possible, so there is no need to read the docs.

**Comment by marcvangend** [comment]
Thanks Nico. I totally understand you wanted to get it working first. Of course the wiki is great for documentation too.

You are right that most (all?) features seem to work out of the box. I just didn't expect it would be that easy :laughing: 

The two features I was most curious about (and triggered me to create this issue), are the auto-configuring datasource and the DDEV terminal. For the datasource I expected I had to manually add/enable the DDEV database. Instead it was already there, I just needed a little patience while it was configuring/connecting/whatever. A tooltip could clarify that. The terminal was a bit harder to find, I don't think I ever clicked that little down chevron in the terminal pane before. Especially for something like this, slightly hidden, a tooltip would be helpful.

I really like your approach of making things auto-configuring and self-explanatory, with some tooltips to get people started. That said, written documentation is still important. When I install a plugin and see five tooltips, I will happily click "Got it" five times, but probably remember two at best.

**Comment by nico-loeber** [comment]
Thank you for clarifying @marcvangend!
This would by my solution for this issue:
- I already increased the priority of the interactive tutorial and made it part of the 1.0.0 milestone (Was planned as a nice to have after release before)
- As soon as we are a feature complete and the behavior won't change, I will document every feature and how to use it in the Wiki.

Do you agree with this solution?
In the meantime you may of course contribute to the wiki if you like.

**Comment by marcvangend** [comment]
> Do you agree with this solution?

Absolutely, I think this is the way to go 👌

**Comment by nico-loeber** [comment]
@juulliian has added basic feature documentation, which can be found here: https://github.com/php-perfect/ddev-intellij-plugin/wiki/Features
The documentation will be expanded over time. I will close this issue.
