### ISSUE TITLE
Default "DDEV" server name isn't compatible with all xdebug scenarios

### ISSUE THREAD

**Issue by ultimike** [php-perfect/ddev-intellij-plugin#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

By default, when this plugin creates the "DDEV" configuration "PHP | Servers", it uses the name "DDEV" with a "Host" of `SITE_NAME.ddev.site`. This works for most debugging situations.

I have found, however, that when debugging PhpUnit tests, the name "DDEV" must be replaced with the same value as the "Host" (`SITE_NAME.ddev.site`).

### Steps to reproduce

1. Try to debug a PhpUnit test using the default server configuration - it won't work.  
2. Change the "PHP | Servers" name from `DDEV` to `SITE_NAME.ddev.site` and debugging of PhpUnit tests will work.

My setup is pretty standard, I am using the standard phpunit.xml file from Drupal core moved to the project root (with updated paths). 

When I make this change above, I think the DDEV plugin recreates a new server configuration with the name "DDEV". This does not affect my ability to use xdebug on PhpUnit tests nor non-test-code situations. 

### Additional context

This is very loosely related to #220

**Comment by rfay** [comment]
I do think this is likely a PhpStorm bug, rather than an issue of the plugin here, but it could obviously be worked around here. 

It could be raised upstream in https://youtrack.jetbrains.com/issues?q=project:%20PhpStorm but would need a very careful repro, which wouldn't use this plugin. But it should be demonstrable by manually creating the "server".

And let's get them to change the name "server" to something useful while we're at it :)

**Comment by ultimike** [comment]
So, demonstrate how to reproduce the issue when manually creating a "Server" and showing how Xdebug doesn't work unless the "Name" is the same?

**Comment by rfay** [comment]
Yes, that's what I'm suggesting. It's too difficult a problem for the PhpStorm folks unless a great and simple repro is provided.

**Comment by nico-loeber** [comment]
Thanks for reporting @ultimike!

The generated config could be changed to this naming pattern, but it makes it more complicated to update it.
If the config name is changed by the ddev configuration (name of the ddev project) a new configuration would be generated instead of updating the current one, as the plugin no longer knows the old name of the project.
Of course you could work with pattern matching and remove *.ddev.site configurations that do not fit the current project name, but maybe someone added them by intention.
So please keep me updated regarding the PHPStorm issue.

**Comment by kevinquillen** [comment]
This doesn't work out of the box for Kernel/Functional tests especially ones that test HTTP, session, cookie or routing data.

I had to do the following:

- Change the name of the debug connection from DDEV to the actual DDEV domain (same as the HOST value)
- Add a _second_ connection in this same screen with the name set to the DDEV domain but the HOST as 'localhost'
- For both connections, map the project root to /var/www/html and the project webroot to /var/www/html/web (or /var/www/html/docroot, depending)

Only until I did that could I run xdebug to inspect all test types.

<img width="778" alt="image" src="https://github.com/php-perfect/ddev-intellij-plugin/assets/362176/8403f3eb-ea97-431a-9308-f9d75a7dea92">

**Comment by rfay** [comment]
The reality is that the server name should be the canonical name of the project, for best usability. Thanks all for following up on this. It would be great to change the "server" name to the site FQDN, as PhpStorm does by default and always has.

**Comment by kevinquillen** [comment]
Yes, I ran into this same issue with Docker4Drupal in the past. The IDE key was PHPSTORM and the server name also had to be PHPSTORM or it wouldn't work.

https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L37

https://wodby.com/docs/1.0/stacks/drupal/local/#xdebug

Even though the docs say the host name doesn't matter there, I always found that it did along with name.

**Comment by RuZniki** [comment]
Hey, I also get the same problem with ddev, PHP Storm, xdebug.
I was trying to run PHP unit tests from PHP Storm UI, and the mapping didn't work.
Running PHP unit tests from CLI also have this issue.
And it was so unexpected that changing server name will fix this, I think that main thing is host settings.

As solution/workaround 

1. provide notification message, when server configuration created that it's better to change server name. 
2. Update ddev documentation page https://ddev.readthedocs.io/en/latest/users/debugging-profiling/step-debugging/. Put info about server name.

**Comment by rfay** [comment]
We should turn this into an issue.

**Comment by rfay** [comment]
I'm writing an issue.
