### ISSUE TITLE
Incompatible with PhpStorm 2024.2

### ISSUE THREAD

**Issue by blankse** [php-perfect/ddev-intellij-plugin#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

After upgrading to PhpStorm 2024.2 I'm getting this message:
`Incompatible: requires IDE build 241.* or earlier`

**Comment by thomaskieslich** [comment]
If someone like to test a mixed build from issue 350 and 351 on macos Sonoma this is a mixed Build from the two pull requests.
[ddev-intellij-plugin-0.0.1-dev.zip](https://github.com/user-attachments/files/16641953/ddev-intellij-plugin-0.0.1-dev.zip)

**Comment by JonMcLScope** [comment]
No errors received on startup and plugin functionality seems to be working for me on Sonoma with PHPStorm 2024.2.

I hardly know enough to do extensive testing, but plugin detected ddev running and PHPStorm database connection is configured correctly.

**Comment by AkibaAT** [comment]
Here's a new build integrating all of my PRs:
[ddev-intellij-plugin-0.0.1-dev.zip](https://github.com/user-attachments/files/16648849/ddev-intellij-plugin-0.0.1-dev.zip)

**Comment by AkibaAT** [comment]
Update after regression fix in #352 
[ddev-intellij-plugin-0.0.1-dev.zip](https://github.com/user-attachments/files/16651921/ddev-intellij-plugin-0.0.1-dev.zip)

**Comment by rfay** [comment]
I always appreciate all the work that goes into each of these updates, and know it's nontrivial. (Thanks so much @AkibaAT and @nico-loeber )

I know you've already been thinking about this, and I thought I'd seen conversation about it, but is there any way to make it so every release of PhpStorm doesn't require this level of effort? Do all PhpStorm plugins have to have this level of effort for every release of the product?

**Comment by nico-loeber** [comment]
There is room for improvement regarding the release workflow, like adding the ability to test the plugin with EAP versions so we can fix potential issues earlier. I tried two times to implement some sort of an EAP branch with automated tests and stuff like that but failed. Pull requests are very welcome!
We also had quite a lot of problems with bugs of the [IntelliJ Gradle Plugin](https://github.com/JetBrains/intellij-platform-gradle-plugin) in the past, which provides all the pipeline tasks to test, sign and release the plugin.

A big problem of this plugin is, that we are messing around with a lot of internal API of the IDE. Most plugins just add independent functionality, or add support for syntax highlighting, or tool integrations. For such use cases there is a defined and stable API. The ddev plugin changes settings of the IDE that are not meant to be changed and uses much lower level API which is not that stable, so there are smaller adaptions of the business logic necessary because of deprecations or sometimes even because of changed behavior or removals without previous depreaction.
Thats the reason why we can not just set the compatibility to >= 2024.*, because it will probably break.

**Comment by MelaineGerard** [comment]
I think it really depends on how you setup your project. For example, I'm using the Stimulus plugin from [anstarovoyt](https://github.com/anstarovoyt/intellij-stimulus) and with his workflow, updates seems pretty easy as he just have to update the gradle.properties to add compatibility to new version. (Yeah he does no have any github actions, so no automated tests)

**Comment by kaystrobach** [comment]
@nico-loeber maybe it makes sense to ask @jetbrains for help directly? They are usually very helpfull and maybe you can get a more stable api for some of the main functionality. If ok for you, I would try to contact them via twitter? and point to that issue ...

**Comment by graham73may** [comment]
Has this reached a stage where we can get a new release so it's installable through Marketplace? 

https://plugins.jetbrains.com/plugin/18813-ddev-integration/versions

**Comment by nico-loeber** [comment]
Yes, all pull requests from @AkibaAT are reviewed and merged.
Some smaller changes are required to make SonarCloud happy again, then a new version will be released.
I hope for tomorrow as I am busy this evening.

**Comment by rfay** [comment]
@nico-loeber could you please pin this issue.

**Comment by rfay** [comment]
Just a consolation note. Jetbrains' own AI plugin has the same problem right now, so it's obvious that this is a hard problem.

<img width="725" alt="image" src="https://github.com/user-attachments/assets/87400271-96c3-4c97-9ded-0b6e78c4ca49">
