### ISSUE TITLE
Tools -> DDEV -> Configure is greyed out on existing project (ddev config --auto --php-version=5.6????)

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

I kept trying to figure out how to use Tools -> DDEV -> Configure to reconfigure a project (at least that's what I thought I wanted to do) but it was always greyed out. 

Now I see that "Configure" is apparently only available for projects that have never had `ddev config` run.

However, when I did use a project that hadn't been configured, I see

`ddev config --auto --php-version 5.6`

Which really isn't what we want. I know of no reason to ever provide `--php-version`, and certainly not a version that has been out of support for many years. 

`ddev config --auto` does normally succeed, and is a good path, but please don't add php version 5.6.

### Steps to reproduce

* Create a project or empty directory
* Open it in PhpStorm as a project
* Choose Tools->DDEV->Configure

See `ddev config --auto --php-version 5.6`

**Comment by nico-loeber** [comment]
The `--php-version` parameter is based on the language level configured in your IDE.
Your IDE will determine your language level automatically based on the constraints in your composer.json or by the language features used in your existing project.
As your IDE does base it's decission on parsing the composer.json or all of your project files it should have know best which php version to use.
In case you configure ddev in an empty project, it might happen that PHPStorm will fallback to php 5.6.

The config option is only enabled in projects in which ddev is not configured yet, because otherwise you can do all the configuration by editing the `.ddev/config.yml`. You should notice that you have auto completion for possible configuration values, validation of the overall config and a description of the configurable parameters if you hover them.

In my opinion configuring ddev with this assistance is the fastest and most felixble way that does not require any changes to the plugin for new ddev features.

**Comment by rfay** [comment]
FYI you don't need --auto with --php-version. Just `ddev config --php-version` will do the same thing. `--auto` is just there to prevent the default prompting behavior when people don't want it, and they usually don't need it.

**Comment by rfay** [comment]
I confirm that it's using PhpStorm's PHP version, and that PhpStorm defaults to the (terrible) 5.6 value. I can see that using PhpStorm's version is a reasonable choice.

**Comment by nico-loeber** [comment]
Great!
I did also think about a feature to keep the language level of phpstorm and the `.ddev/config.yml` in sync after the initial setup.
But this feature is part of an expansion stage.
Closing this for now.

**Comment by rfay** [comment]
Hope you caught the note that `--auto` is not even useful when used with another config option like `--php-version`.

**Comment by nico-loeber** [comment]
> FYI you don't need --auto with --php-version. Just ddev config --php-version will do the same thing.

`--php-version` isn't always present, as you can install the plugin in IDEs without PHP Support. It think in this case `--auto` was neccessary to run config in a non interactive way with auto configuration of the web root.
